name = "MeshViewer"
uuid = "f005f57a-73ba-4db4-9eca-a34f8f0e4df1"
authors = ["Thomas Cheng thomasc791@gmail.com"]
version = "1.0.0-DEV"

[deps]
CImGui = "5d785b6c-b76f-510e-a07c-3070796c7e87"
GLFW = "f7f18e0c-5ee9-5ccd-a5bf-e8befd85ed98"
ModernGL = "66fc600b-dfda-50eb-8b99-91cfa97b1301"

[compat]
CImGui = "5.1.1"
GLFW = "3.4.3"
ModernGL = "1.1.8"
julia = "1.11.2"
